### ISSUE TITLE
Buffalo's chopper being afflicted with sudden altitude loss on Tanoa.

### ISSUE THREAD

**Issue by FlamesOfAzure** [7Cav/7Cav-Insurgency#46]
FYI, there's something strange going on with Buffalo's chopper on Tanoa.

3 separate times after takeoff and flying about 1km or so away from base, the chopper ends up dropping altitude severely to the point of crashing.

Thought it was pilot error at first as it was night and really foggy, however, on the third attempt I watched the altitude level. We were slowly climbing up to about 100m and then within seconds it dropped like a brick.

**Comment by Whitsel** [comment]
Had anybody been able to reproduce this since? I've asked around a couple of times but haven't heard about it since

**Comment by FlamesOfAzure** [comment]
Guess it was a one off thing... that or maybe somebody was messing with the chopper ropes without anyone realizing? Just strange all around as it happened with three separate pilots back-to-back.

Regardless, if it's not happening anymore then that's good :).
