### ISSUE TITLE
New Arsenal Framework Issues

### ISSUE THREAD

**Issue by 7cavZlobinN** [7Cav/7Cav-Insurgency#47]
execVM "scripts\arsenal\fn_arsenalGeneral.sqf"; does not seem to work in any of the functions, nor does [] call scripts_fnc_arsenalGeneral;

**Comment by Whitsel** [comment]
I'll have to look into this when I get back from the field. For now best advice I can give is to reference my template mission that I linked somewhere else as it was working on there. Hopefully I'll be back within a week or so

**Comment by Whitsel** [comment]
> execVM "scripts\arsenal\fn_arsenalGeneral.sqf"; does not seem to work in any of the functions, nor does [] call scripts_fnc_arsenalGeneral;

Can you elaborate a bit on exactly what the issue was? I'm not able to recreate it on my end in local MP. The general arsenal appears to be appearing for everybody.

**Comment by Whitsel** [comment]
Upon closer inspection, I realize that no optics or bipod/grips were being added to anything. I've added _sights and _bipods on my end and will include it in the arsenal pull request

**Comment by Whitsel** [comment]
New framework is in place and functional
