### ISSUE TITLE
TFC Smidt & Bender scope missing from Longshot arsenal

### ISSUE THREAD

**Issue by 7cavZlobinN** [7Cav/7Cav-Insurgency#49]
Possible class re-naming due to TFC update.

**Comment by Whitsel** [comment]
Classname was changed from "tfc_wa_lrps" to the following
"tfc_wa_3_20_x50",
"tfc_wa_4_16_x56",
"tfc_wa_5_25_x56_high",
"tfc_wa_5_25_x56_low",

Will be updated in new arsenal framework
