### ISSUE TITLE
Buffalo-1 Door Gunner pointed into helicopter

### ISSUE THREAD

**Issue by SyniRon** [7Cav/7Cav-Insurgency#77]
![2021-03-08_14-43-55](https://user-images.githubusercontent.com/66834451/110373057-0b7bc600-801d-11eb-8d2c-438668e7ef1c.jpg)

The door gunner gun is pointed into the helicopter, this persists across maps.

**Comment by SyniRon** [comment]
![2021-03-08_14-46-58](https://user-images.githubusercontent.com/66834451/110373150-2c441b80-801d-11eb-8c58-b878fb92df74.jpg)

**Comment by Whitsel** [comment]
This is an issue with RHS and they are already tracking and working on a fix
